---
redis:
  host: redis
  port: 6379
s3:
  bucket_name: 98106a91-edae-4dbd-8fe3-daf39f28999b
  authentication_email_key_prefix: authentication-email
yostar_login:
  email_addresses:
    - div5e6m6@cryolite.net
sniffer:
  logging:
    level: INFO
    file:
      path: /var/log/kanachan-reviewer/sniffer{}.log
      max_bytes: 10485760
      backup_count: 10
    redis:
      key: log.sniffer
      max_entries: 1024
fetcher:
  logging:
    level: INFO
    file:
      path: /var/log/kanachan-reviewer/fetcher{}.log
      max_bytes: 10485760
      backup_count: 10
    redis:
      key: log.fetcher
      max_entries: 1024
analyzer:
  logging:
    level: INFO
    file:
      path: /var/log/kanachan-reviewer/analyzer{}.log
      max_bytes: 10485760
      backup_count: 10
    redis:
      key: log.analyzer
      max_entries: 1024
